previews:
  generation: manual

services:
  # ==============================
  # 1) API (Express + PostgreSQL)
  # ==============================
  - type: web
    name: gouzepe-api
    runtime: node
    rootDir: api
    region: frankfurt       # proche de l'Afrique de l'Ouest
    plan: starter
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      # Connexion Postgres (Render injecte l'URL privée)
      - key: DATABASE_URL
        fromDatabase:
          name: gouzepe-db
          property: connectionString
      # Forcer SSL côté pg (node-postgres)
      - key: PGSSL
        value: "true"
      # Secret JWT (Render le génère si absent)
      - key: JWT_SECRET
        generateValue: true
      # Origins autorisés pour CORS + Socket.IO (séparés par virgule)
      # ⚠️ Ajuste "gouzepe-static" si tu choisis un autre nom pour le site statique
      - key: CORS_ORIGIN
        value: "https://gouzepe-static.onrender.com,http://localhost:5500,http://localhost:5173"
      # Options diverses de l'app (facultatif)
      - key: TEAM_KEY_LEN
        value: "4"
      - key: EMAIL_DOMAIN
        value: "gouzepe.local"

  # ==============================
  # 2) Frontend statique (web/)
  # ==============================
  - type: web
    name: gouzepe-static
    runtime: static
    staticPublishPath: ./web
    region: frankfurt
    plan: free
    buildCommand: 'true'  # pas de build, on publie directement /web
    headers:
      # Durcir un peu la surface (tu peux adapter au besoin)
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=2592000, immutable
      - path: /fonds/*
        name: Cache-Control
        value: public, max-age=2592000, immutable
    routes:
      # Rediriger la racine vers login.html (car /web n'a pas d'index.html)
      - type: rewrite
        source: /
        destination: /login.html

databases:
  - name: gouzepe-db
    databaseName: efoot
    plan: free
